/* 
* version.h 
* 
*/ 

#ifndef INC_VERSION_H_ 
#define INC_VERSION_H_ 

#define STRINGIFY(x) #x 
#define EXPAND_AND_STRINGIFY(x) STRINGIFY(x) 

#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 0
#define FW_VERSION_PATCH 2
#define FW_VERSION_SUFFIX 16

#define FW_VERSION_STRING "PowerCUBE v" EXPAND_AND_STRINGIFY(FW_VERSION_MAJOR) "." EXPAND_AND_STRINGIFY(FW_VERSION_MINOR) "." EXPAND_AND_STRINGIFY(FW_VERSION_PATCH) "-" EXPAND_AND_STRINGIFY(FW_VERSION_SUFFIX) 


#endif /* INC_VERSION_H_ */ 
